### ISSUE TITLE
inspection fails on:Unrecognized field "datesAndPictures

### ISSUE THREAD

**Issue by sharon-pl** [lovecoding530/SafetyApp-chat#45]
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "datesAndPictures" (class com.peled.backend.model.v2.inspection.driver.DriverDataV2), not marked as ignorable (12 known properties: "driverLicenseNumber", "driverId", "driverHatzharatNahagDate", "driverLicenceDate", "fullName", "driverAddress", "driverTokefSnapshot", "driverHomasDate", "remarks", "driverManofDate", "driverIsKavua", "driverLicenseType"])

**Comment by kpstar** [comment]
fixed
